-- phpMyAdmin SQL Dump
-- version 4.0.4
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le: Dim 10 Novembre 2013 à 18:34
-- Version du serveur: 5.6.12-log
-- Version de PHP: 5.4.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `u305473976_tgt`
--
CREATE DATABASE IF NOT EXISTS `u305473976_tgt` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
USE `u305473976_tgt`;

-- --------------------------------------------------------

--
-- Structure de la table `tgt_posthands`
--

CREATE TABLE IF NOT EXISTS `tgt_posthands` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_users` int(11) NOT NULL,
  `title` varchar(50) COLLATE utf8_bin NOT NULL,
  `hand` mediumtext COLLATE utf8_bin NOT NULL,
  `thinkingprocess` varchar(10000) COLLATE utf8_bin NOT NULL,
  `image1` varchar(1000) COLLATE utf8_bin DEFAULT NULL,
  `image2` varchar(1000) COLLATE utf8_bin DEFAULT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `enable` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=66 ;

--
-- Contenu de la table `tgt_posthands`
--

INSERT INTO `tgt_posthands` (`id`, `id_users`, `title`, `hand`, `thinkingprocess`, `image1`, `image2`, `date`, `enable`) VALUES
(59, 1, 'KK au co (test)', 'Poker Stars No-Limit Hold''em, $0.10 BB (6 handed) - Poker Stars Converter Tool from http://flopturnriver.com<br>\n<br>\nHero (Button) ($17.79)<br>\nSB ($13.68)<br>\nBB ($13.53)<br>\nUTG ($6.40)<br>\nMP ($6.52)<br>\nCO ($8.57)<br>\n<br>\n<b>Preflop</b>: Hero is Button with K<img src="http://www.flopturnriver.com/pokerforum/images/smilies/diamond.gif">, K<img src="http://www.flopturnriver.com/pokerforum/images/smilies/spade.gif"><br>\n<font color=#666666><i>2 folds</i></font>, <font color=#CC3333>CO raises $0.30</font>, <font color=#CC3333>Hero raises $1</font>, <font color=#666666><i>2 folds</i></font>, CO calls $0.70<br>\n<br>\n<b>Flop</b>: ($2.15) A<img src="http://www.flopturnriver.com/pokerforum/images/smilies/diamond.gif">, A<img src="http://www.flopturnriver.com/pokerforum/images/smilies/spade.gif">, 6<img src="http://www.flopturnriver.com/pokerforum/images/smilies/spade.gif"> <font color=#009B00>(2 players)</font><br>\nCO checks, Hero checks<br>\n<br>\n<b>Turn</b>: ($2.15) 10<img src="http://www.flopturnriver.com/pokerforum/images/smilies/spade.gif"> <font color=#009B00>(2 players)</font><br>\nCO checks, <font color=#CC3333>Hero bets $1</font>, <font color=#CC3333>CO raises $2.30</font>, Hero calls $1.30<br>\n<br>\n<b>River</b>: ($6.75) 2<img src="http://www.flopturnriver.com/pokerforum/images/smilies/heart.gif"> <font color=#009B00>(2 players)</font><br>\n<font color=#CC3333>CO bets $4</font>, <font color=#666666><i>Hero folds</i></font><br>\n<br>\n<b>Total pot:</b> $6.75<br>\n<br>\nResults below:  <br>\nCO didn''t show</font><br>\n', 'test', '', '', '2013-11-07 22:58:41', 1),
(60, 2, 'tob', '<style type="text/css">.wt_rel td {font-weight: bold;}.hheader	 { font-weight: bold; font-variant: small-caps; font-size : 13px; color: black;}.wt_hh1{ font-weight: bold; font-variant: small-caps; font-size : 12px; color: black; }.wt_h2{ font-variant: small-caps; font-size : 11px; color: black; }.wt_t1{ font-size : 11px; color: black; background-color: #eeeeee; border-collapse: separate; border-spacing: 4px; border:1px solid #DDDDFF;}.wt_blue {color:blue}.weaktight_hand {font-size: 11px;}.wt_ul {list-style:none;}</style><div class="weaktight_hand"><h2 class="wt_hheader">â‚¬0.10/â‚¬0.25  No Limit Holdem â€¢ 5 Players â€¢ PartyPoker</h2><h2 class="wt_h2">Generated by <a href="http://weaktight.com">weaktight.com</a>.</h2><div style="padding:4px; margin:auto; border-top:2px solid #ccc;"><table class="wt_t1" cellspacing="4" cellpadding="2" border="0" ><tr ><td>UTG<td>Twido<td><span class="bluenb">â‚¬27.56</span><td><tr/><tr ><td>CO<td>ANTONIO113<td><span class="bluenb">â‚¬7.08</span><td><tr/><tr class="wt_rel"><td>BTN<td>Hero<td><span class="bluenb">â‚¬48.01</span><td><tr/><tr ><td>SB<td>cocokho<td><span class="bluenb">â‚¬39.30</span><td><tr/><tr class="wt_rel"><td>BB<td>stern1409<td><span class="bluenb">â‚¬46.80</span><td><tr/></table></div><div class="street1" style="border-top:2px solid #ccc;  background-color: #EDF5ED; padding:3px;"><ul class="wt_ul"><li><span class="wt_hh1"> Pre-Flop</span> (<span class="wt_blue">â‚¬0.35</span>, 5 players)<span style="font-weight:bold;">Hero is BTN</span><li style="padding-left:8px;"><img width=42 height=55 alt="sT" title="sT" src="http://weaktight.com/img/d54c/sT.gif" /> <img width=42 height=55 alt="cQ" title="cQ" src="http://weaktight.com/img/d54c/cQ.gif" /></ul><div class="area2" style="padding-left:50px;"><span style="color:grey"><i>2 folds</i></span>, <span style="color:red"><b>Hero raises to â‚¬0.75</b></span>, <span style="color:grey"><i>1 fold</i></span>, stern1409 calls â‚¬0.50<div class=sk><table width="100%"></table></div></div></div><div class="street2"><ul class="wt_ul"><li ><span class="wt_hh1"> Flop</span> (<span class="wt_blue">â‚¬1.60</span>, 2 players)<li style="padding: 3px 3px 3px 8px;"> <img width=42 height=55 alt="sJ" title="sJ" src="http://weaktight.com/img/d54c/sJ.gif" /> <img width=42 height=55 alt="s2" title="s2" src="http://weaktight.com/img/d54c/s2.gif" /> <img width=42 height=55 alt="cT" title="cT" src="http://weaktight.com/img/d54c/cT.gif" /></ul><div class="area2" style="padding-left:50px;">stern1409 checks, Hero bets â‚¬1.12, stern1409 calls â‚¬1.12<div class=sk><table width="100%"></table></div></div></div><div class="street1" style="background-color: #EDF5ED; padding:3px;"><ul class="wt_ul"><li ><span class="wt_hh1"> Turn</span> (<span class="wt_blue">â‚¬3.84</span>, 2 players)<li style="padding-left:8px;"><img width=42 height=55 alt="c6" title="c6" src="http://weaktight.com/img/d54c/c6.gif" /></ul><div class="area2" style="padding-left:50px;">stern1409 bets â‚¬0.75, <span style="color:red"><b>Hero raises to â‚¬3</b></span>, stern1409 calls â‚¬2.25<div class=sk><table width="100%"></table></div></div></div><div class="street2"><ul class="wt_ul"><li><span class="wt_hh1"> River</span> (<span class="wt_blue">â‚¬9.84</span>, 2 players)<li style="padding-left:8px;"><img width=42 height=55 alt="c7" title="c7" src="http://weaktight.com/img/d54c/c7.gif" /></ul><div class="area2" style="padding-left:50px;">stern1409 bets â‚¬1.50, <span style="color:red"><b>Hero raises to â‚¬8.25</b></span>, <span style="color:grey"><i>stern1409 folds</i></span><div class=sk><table width="100%"></table></div></div></div><div class=street1 style="border-top:2px solid #ccc;background-color: #EDF5ED; padding:3px;"><div class="h1h"><ul class="wt_ul"><li><span class="wt_hh1"> Final Pot:</span> <span class="wt_blue">â‚¬12.84</span></ul></div><div class="area2"></div><div class=street2><div class="area2"><ul class="wt_ul"><li style="font-size:14px; font-weight:bold;">Hero wins <span class="wt_blue" style="font-size:14px;">â‚¬25.49 (net  â‚¬12.37)</span><li>stern1409 lost <span class="wt_blue">â‚¬6.37</span></li></ul></div></div></div></div>', '64/24\n5bet fold preflop ou cold call in the dark???', '', '', '2013-11-08 20:40:49', 1),
(63, 5, 'AJ sur 7JKK8', '<style type="text/css">.wt_rel td {font-weight: bold;}.hheader	 { font-weight: bold; font-variant: small-caps; font-size : 13px; color: black;}.wt_hh1{ font-weight: bold; font-variant: small-caps; font-size : 12px; color: black; }.wt_h2{ font-variant: small-caps; font-size : 11px; color: black; }.wt_t1{ font-size : 11px; color: black; background-color: #eeeeee; border-collapse: separate; border-spacing: 4px; border:1px solid #DDDDFF;}.wt_blue {color:blue}.weaktight_hand {font-size: 11px;}.wt_ul {list-style:none;}</style><div class="weaktight_hand"><h2 class="wt_hheader">â‚¬0.05/â‚¬0.10  No Limit Holdem â€¢ 5 Players â€¢ PokerStars</h2><h2 class="wt_h2">Generated by <a href="http://weaktight.com">weaktight.com</a>.</h2><div style="padding:4px; margin:auto; border-top:2px solid #ccc;"><table class="wt_t1" cellspacing="4" cellpadding="2" border="0" ><tr class="wt_rel"><td>UTG<td>Squadl<td><span class="bluenb">â‚¬10</span><td><tr/><tr class="wt_rel"><td>CO<td>mounierlyon<td><span class="bluenb">â‚¬7.30</span><td><tr/><tr ><td>BTN<td>MACDA22<td><span class="bluenb">â‚¬9.46</span><td><tr/><tr ><td>SB<td>slbvinil<td><span class="bluenb">â‚¬18.08</span><td><tr/><tr ><td>BB<td>FredHampton<td><span class="bluenb">â‚¬10.83</span><td><tr/></table></div><div class="street1" style="border-top:2px solid #ccc;  background-color: #EDF5ED; padding:3px;"><ul class="wt_ul"><li><span class="wt_hh1"> Pre-Flop</span> (<span class="wt_blue">â‚¬0.15</span>, 5 players)<span style="font-weight:bold;">Hero is UTG</span><li style="padding-left:8px;"><img width=42 height=55 alt="dJ" title="dJ" src="http://weaktight.com/img/d54c/dJ.gif" /> <img width=42 height=55 alt="hA" title="hA" src="http://weaktight.com/img/d54c/hA.gif" /></ul><div class="area2" style="padding-left:50px;"><span style="color:red"><b>Squadl raises to â‚¬0.40</b></span>, mounierlyon calls â‚¬0.40, <span style="color:grey"><i>3 folds</i></span><div class=sk><table width="100%"></table></div></div></div><div class="street2"><ul class="wt_ul"><li ><span class="wt_hh1"> Flop</span> (<span class="wt_blue">â‚¬0.95</span>, 2 players)<li style="padding: 3px 3px 3px 8px;"> <img width=42 height=55 alt="cJ" title="cJ" src="http://weaktight.com/img/d54c/cJ.gif" /> <img width=42 height=55 alt="s7" title="s7" src="http://weaktight.com/img/d54c/s7.gif" /> <img width=42 height=55 alt="sK" title="sK" src="http://weaktight.com/img/d54c/sK.gif" /></ul><div class="area2" style="padding-left:50px;">Squadl bets â‚¬0.50, mounierlyon calls â‚¬0.50<div class=sk><table width="100%"></table></div></div></div><div class="street1" style="background-color: #EDF5ED; padding:3px;"><ul class="wt_ul"><li ><span class="wt_hh1"> Turn</span> (<span class="wt_blue">â‚¬1.95</span>, 2 players)<li style="padding-left:8px;"><img width=42 height=55 alt="cK" title="cK" src="http://weaktight.com/img/d54c/cK.gif" /></ul><div class="area2" style="padding-left:50px;">Squadl bets â‚¬0.80, mounierlyon calls â‚¬0.80<div class=sk><table width="100%"></table></div></div></div><div class="street2"><ul class="wt_ul"><li><span class="wt_hh1"> River</span> (<span class="wt_blue">â‚¬3.55</span>, 2 players)<li style="padding-left:8px;"><img width=42 height=55 alt="c8" title="c8" src="http://weaktight.com/img/d54c/c8.gif" /></ul><div class="area2" style="padding-left:50px;">Squadl bets â‚¬1.70, mounierlyon calls â‚¬1.70<div class=sk><table width="100%"></table></div></div></div><div class=street1 style="border-top:2px solid #ccc;background-color: #EDF5ED; padding:3px;"><div class="h1h"><ul class="wt_ul"><li><span class="wt_hh1"> Final Pot:</span> <span class="wt_blue">â‚¬6.95</span></ul></div><div class="area2"><ul class="wt_ul"><li style="padding: 4px;"><span class=hh21> Squadl shows two pair, Kings and Jacks</span><li style="padding-left:8px;"><img width=42 height=55 alt="dJ" title="dJ" src="http://weaktight.com/img/d54c/dJ.gif" /><img width=42 height=55 alt="hA" title="hA" src="http://weaktight.com/img/d54c/hA.gif" /></ul><ul class="wt_ul"><li style="padding: 4px;"><span class=hh21> mounierlyon shows three of a kind, Kings</span><li style="padding-left:8px;"><img width=42 height=55 alt="dK" title="dK" src="http://weaktight.com/img/d54c/dK.gif" /><img width=42 height=55 alt="sQ" title="sQ" src="http://weaktight.com/img/d54c/sQ.gif" /></ul></div><div class=street2><div class="area2"><ul class="wt_ul"><li style="font-size:14px; font-weight:bold;">mounierlyon wins <span class="wt_blue" style="font-size:14px;">â‚¬6.50 (net  â‚¬3.10)</span><li>Squadl lost <span class="wt_blue">â‚¬3.40</span></li></ul></div></div></div></div>', 'Flop: Je n''ai plus les stats du villain en question. Je barrel flop en value contre tout ses floats et FD.\nTurn: Carte parfaite qui rÃ©duit les combos de Kx de sa range, standard 2nd barrel en value sur ses FD/OESD/Jx.\nRiver: Y''a plus bcp de value Ã  faire, tout les busted OESD/FD vont fold, reste plus que Jx. Le check/call est p-e mieux ici?\n', '', '', '2013-11-08 21:36:05', 1),
(64, 1, 'AKo vs 2 vilain', 'Poker Stars No-Limit Hold''em, $0.10 BB (5 handed) - Poker Stars Converter Tool from http://poker-tools.flopturnriver.com/Hand-Converter.php<br>\n<br>\nUTG ($11.18)<br>\nMP ($9.95)<br>\nHero (Button) ($12.11)<br>\nSB ($10)<br>\nBB ($8.84)<br>\n<br>\n<b>Preflop</b>: Hero is Button with A<img src="http://www.flopturnriver.com/pokerforum/images/smilies/club.gif">, K<img src="http://www.flopturnriver.com/pokerforum/images/smilies/heart.gif"><br>\n<font color=#CC3333>UTG raises $0.20</font>, <font color=#CC3333>MP raises $0.60</font>, <font color=#CC3333>Hero raises $2</font>, <font color=#666666><i>2 folds</i></font>, UTG calls $1.80, MP calls $1.40<br>\n<br>\n<b>Flop</b>: ($6.15) 2<img src="http://www.flopturnriver.com/pokerforum/images/smilies/spade.gif">, Q<img src="http://www.flopturnriver.com/pokerforum/images/smilies/spade.gif">, 3<img src="http://www.flopturnriver.com/pokerforum/images/smilies/club.gif"> <font color=#009B00>(3 players)</font><br>\nUTG checks, MP checks, Hero checks<br>\n<br>\n<b>Turn</b>: ($6.15) 6<img src="http://www.flopturnriver.com/pokerforum/images/smilies/spade.gif"> <font color=#009B00>(3 players)</font><br>\nUTG checks, MP checks, Hero checks<br>\n<br>\n<b>River</b>: ($6.15) 3<img src="http://www.flopturnriver.com/pokerforum/images/smilies/heart.gif"> <font color=#009B00>(3 players)</font><br>\n<font color=#CC3333>UTG bets $1.20</font>, MP calls $1.20, <font color=#666666><i>Hero folds</i></font><br>\n<br>\n<b>Total pot:</b> $8.55<br>\n<br>\nResults below:  <br>\nUTG had K<img src="http://www.flopturnriver.com/pokerforum/images/smilies/club.gif">, K<img src="http://www.flopturnriver.com/pokerforum/images/smilies/spade.gif"> (two pair, Kings and threes).<br>\nMP didn''t show<br>\nOutcome: UTG won $8.17</font><br>\n', 'UTG: 54/41 sur 125 hands\nMP: 40/21 sur 53\n\nIci avec AKo, je 4bet mais quand il call je sent que je suis pas bien et je dÃ©cide de jouer en check sur tout le long, river je fold. Bien jouÃ©?', '', '', '2013-11-09 12:07:27', 1),
(65, 1, '9Ts en 4way', 'Poker Stars No-Limit Hold''em, $0.10 BB (5 handed) - Poker Stars Converter Tool from http://poker-tools.flopturnriver.com/Hand-Converter.php<br>\n<br>\nButton ($11.95)<br>\nSB ($11.64)<br>\nBB ($10.10)<br>\nHero (UTG) ($16.20)<br>\nMP ($4)<br>\n<br>\n<b>Preflop</b>: Hero is UTG with 10<img src="http://www.flopturnriver.com/pokerforum/images/smilies/diamond.gif">, 9<img src="http://www.flopturnriver.com/pokerforum/images/smilies/diamond.gif"><br>\n<font color=#CC3333>Hero raises $0.40</font>, MP calls $0.30, Button calls $0.40, SB calls $0.35, <font color=#666666><i>1 fold</i></font><br>\n<br>\n<b>Flop</b>: ($1.60) 8<img src="http://www.flopturnriver.com/pokerforum/images/smilies/club.gif">, 2<img src="http://www.flopturnriver.com/pokerforum/images/smilies/diamond.gif">, 7<img src="http://www.flopturnriver.com/pokerforum/images/smilies/spade.gif"> <font color=#009B00>(4 players)</font><br>\nSB checks, Hero checks, MP checks, Button checks<br>\n<br>\n<b>Turn</b>: ($1.60) 5<img src="http://www.flopturnriver.com/pokerforum/images/smilies/club.gif"> <font color=#009B00>(4 players)</font><br>\nSB checks, Hero checks, <font color=#CC3333>MP bets $0.50</font>, Button calls $0.50, <font color=#666666><i>1 fold</i></font>, Hero calls $0.50<br>\n<br>\n<b>River</b>: ($3.10) 3<img src="http://www.flopturnriver.com/pokerforum/images/smilies/club.gif"> <font color=#009B00>(3 players)</font><br>\nHero checks, <font color=#CC3333>MP bets $1</font>, <font color=#666666><i>1 fold</i></font>, <font color=#666666><i>Hero folds</i></font><br>\n<br>\n<b>Total pot:</b> $3.10<br>\n<br>\nResults below:  <br>\nMP didn''t show</font><br>\n', 'Au flop je ne sais vraiment pas quoi faire.<br />J''ai 6 outs   backdoor FD. <br />Je prend le check contre 4 vilain.', '', '', '2013-11-09 20:12:05', 1);

-- --------------------------------------------------------

--
-- Structure de la table `tgt_users`
--

CREATE TABLE IF NOT EXISTS `tgt_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `login` varchar(50) COLLATE utf8_bin NOT NULL,
  `password` varchar(50) COLLATE utf8_bin NOT NULL,
  `enable` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=6 ;

--
-- Contenu de la table `tgt_users`
--

INSERT INTO `tgt_users` (`id`, `login`, `password`, `enable`) VALUES
(1, 'Ricain', 'ricain2', 1),
(2, 'Roup', 'verge', 1),
(3, 'John', 'ricain', 1),
(5, 'Squadl', 'thegrind', 1);

-- --------------------------------------------------------

--
-- Doublure de structure pour la vue `view_all`
--
CREATE TABLE IF NOT EXISTS `view_all` (
`id` int(11)
,`id_users` int(11)
,`title` varchar(50)
,`hand` mediumtext
,`thinkingprocess` varchar(10000)
,`image1` varchar(1000)
,`image2` varchar(1000)
,`date` timestamp
,`hands_enable` int(11)
,`login` varchar(50)
,`users_enable` tinyint(1)
);
-- --------------------------------------------------------

--
-- Structure de la vue `view_all`
--
DROP TABLE IF EXISTS `view_all`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_all` AS select `ph`.`id` AS `id`,`ph`.`id_users` AS `id_users`,`ph`.`title` AS `title`,`ph`.`hand` AS `hand`,`ph`.`thinkingprocess` AS `thinkingprocess`,`ph`.`image1` AS `image1`,`ph`.`image2` AS `image2`,`ph`.`date` AS `date`,`ph`.`enable` AS `hands_enable`,`us`.`login` AS `login`,`us`.`enable` AS `users_enable` from (`tgt_posthands` `ph` join `tgt_users` `us`) where (`ph`.`id_users` = `us`.`id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
