/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Eleclerc;

import Utils.Messages;
import Db.DbConnect;
import Db.DbData;
import EmailSender.EmailSender;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author ricardo
 */
public class AnonymousJFrame extends javax.swing.JFrame {

    private int user;
    
    /**
     * Creates new form AnonymousJFrame
     */
    public AnonymousJFrame(String section, boolean selectablecombobox, int user) 
    {
        initComponents();
        this.user = user;
        fillCombo(section, selectablecombobox);
        try {
            //configurações do jframe
            Configuration.configurationJframe.inicialConfiguration(this);
            this.setTitle("Sugestão");
        } catch (SQLException ex) {
            //Logger.getLogger(InicialJFrame.class.getName()).log(Level.SEVERE, null, ex);
            Messages.messageErrorDb("InicialJFrame (config Jframe)");
        }
    }

    /*
     * Permite preencher a combobox dos dados da BD
     * comboselect = section atual
     * selectable = se true pode se selecionar caso contrario não.
     */
    private void fillCombo(String comboselect, boolean selectable)
    {
        try {
            ResultSet rs = (ResultSet) Db.DbData.getDataTable("section", "", "", "", true);
            while (rs.next()) {
                    jCbxsection.addItem(rs.getString("sec_description"));
                }
            jCbxsection.setSelectedItem(comboselect);
            if(selectable)
            {
                jCbxsection.setEnabled(true);
            }            
        } catch (SQLException ex) {
            //Logger.getLogger(AnonymousJFrame.class.getName()).log(Level.SEVERE, null, ex);
            Messages.messageErrorDb("AnonymousJFrame : fillcombo");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCbxsection = new javax.swing.JComboBox();
        jLblinformation = new javax.swing.JLabel();
        jLabelLogotipo = new javax.swing.JLabel();
        jLabeltextArea = new javax.swing.JLabel();
        jBtnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaComments = new javax.swing.JTextArea();
        jBtnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jCbxsection.setAutoscrolls(true);
        jCbxsection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCbxsection.setEnabled(false);

        jLblinformation.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLblinformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblinformation.setText("Selecciona a sua secção caso deseja:");
        jLblinformation.setToolTipText("Não é obrigatório, pode deixar em anónimo");
        jLblinformation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelLogotipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo01.gif"))); // NOI18N

        jLabeltextArea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabeltextArea.setText("Escreva a sua sugestão:");

        jBtnClose.setText("Fechar");
        jBtnClose.setToolTipText("");
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });

        jTextAreaComments.setColumns(20);
        jTextAreaComments.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextAreaComments.setLineWrap(true);
        jTextAreaComments.setRows(5);
        jTextAreaComments.setAutoscrolls(false);
        jTextAreaComments.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextAreaComments);

        jBtnSubmit.setText("Submeter");
        jBtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnSubmit)
                        .addGap(48, 48, 48)
                        .addComponent(jBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLogotipo, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabeltextArea)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLblinformation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbxsection, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblinformation)
                    .addComponent(jCbxsection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabeltextArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnClose)
                    .addComponent(jBtnSubmit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        if(jTextAreaComments.getText().length() > 0)
        {
            if(Messages.messageQuestion("Pretende fechar sem submeter ?", "Aviso") != 0)
            {
                return;
            }
        }
        //caso seja anonimo fecha tudo
        //caso contrario fecha só a janela e volta a janela main
        if(user == 2)
        {
            DbConnect.dbDisconnect(this);
        }else{
            this.dispose();
        }        
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jBtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitActionPerformed
        if(jTextAreaComments.getText().length() > 0)
        {
            ArrayList field = new ArrayList();
            ArrayList column = new ArrayList();
            
            field.add(this.user);
            field.add(jTextAreaComments.getText());
            field.add(jCbxsection.getSelectedIndex() + 1);

            column.add("com_id_user");
            column.add("com_comments");
            column.add("com_id_section");

            if(DbData.insertData("comment", field, column) > 0)
            {
                //resposta da inserção na BD
                Messages.messageInformation("Sugestão Submetida, obrigado.", "Informação");

                //para enviar o mail
                EmailSender mail = new EmailSender();
                mail.sendEmail("Sugestão Submetida", user, jCbxsection.getSelectedItem().toString(),
                        jTextAreaComments.getText());

                //Desligo me da BD.
                if(user == 2)
                {
                    DbConnect.dbDisconnect(this);
                }else{
                    this.dispose();
                }
            }else{
                Messages.messageInformation("Informação", "Não foi possível Submeter,"
                        + "\n\r contacte o administrador");
            }
        }else{
            Messages.messageInformation("Problema", "Não escreveu nada");
        }
    }//GEN-LAST:event_jBtnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtnSubmit;
    private javax.swing.JComboBox jCbxsection;
    private javax.swing.JLabel jLabelLogotipo;
    private javax.swing.JLabel jLabeltextArea;
    private javax.swing.JLabel jLblinformation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaComments;
    // End of variables declaration//GEN-END:variables
}
