/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Eleclerc;

import Configuration.configurationJframe;
import Db.DbConnect;
import Db.DbData;
import Utils.Messages;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ricardo
 */
public class ConfigurationJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConfigurationJFrame
     */
    public ConfigurationJFrame() {
        initComponents();
        this.setTitle("Configuração Da Aplicação");
        try {
            configurationJframe.inicialConfiguration(this);
        } catch (SQLException ex) {
            //Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            Messages.messageErrorDb("MainJFrame : inicialização jframe");
        }
        loadJframe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelSmtpserver = new javax.swing.JLabel();
        jTextFieldSmtpserver = new javax.swing.JTextField();
        jLabelPort = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabelAuth = new javax.swing.JLabel();
        jComboBoxAuth = new javax.swing.JComboBox();
        jTextFieldFrom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabelCharset = new javax.swing.JLabel();
        jTextFieldCharset = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldImage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTo = new javax.swing.JTextField();
        jButtonClose = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Mail para Sugestão:");

        jLabelSmtpserver.setText("SmtpServer:");

        jLabelPort.setText("Port:");

        jLabelLogin.setText("Login:");

        jLabel2.setText("Password");

        jLabelAuth.setText("Auth:");

        jComboBoxAuth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        jLabel3.setText("From:");

        jLabelCharset.setText("Charset:");

        jLabel4.setText("Image:");

        jLabel5.setText("To:");

        jTextFieldTo.setToolTipText("Só pode inserir um mail");

        jButtonClose.setText("Fechar");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonSave.setText("Guardar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSave)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonClose))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPort)
                                    .addComponent(jLabelSmtpserver)
                                    .addComponent(jLabelLogin)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabelAuth)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabelCharset)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSmtpserver)
                                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldLogin)
                                    .addComponent(jTextFieldPassword)
                                    .addComponent(jComboBoxAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFrom)
                                    .addComponent(jTextFieldCharset)
                                    .addComponent(jTextFieldImage)
                                    .addComponent(jTextFieldTo, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSmtpserver)
                    .addComponent(jTextFieldSmtpserver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPort)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAuth)
                    .addComponent(jComboBoxAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCharset)
                    .addComponent(jTextFieldCharset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        //preparo para o roolback
        DbConnect.setAutocommit(false);
        //elimino os dados que existem
        DbData.deleteDataWithRollB("configuration", "conf_tipo",
                        "Email");
        
        ArrayList tempcolumn = new ArrayList();
        ArrayList tempdata = new ArrayList();
        tempcolumn.add("conf_tipo");
        tempcolumn.add("conf_description");
        tempcolumn.add("conf_value");
        //smtp
        tempdata.add("Email");
        tempdata.add("smtpserver");
        tempdata.add(jTextFieldSmtpserver.getText().toString());        
        DbData.insertDatas("configuration", tempdata, tempcolumn);
        tempdata.clear();
        //port
        tempdata.add("Email");
        tempdata.add("port");
        tempdata.add(jTextFieldPort.getText().toString());        
        DbData.insertDatas("configuration", tempdata, tempcolumn);
        tempdata.clear();
        //user
        tempdata.add("Email");
        tempdata.add("user");
        tempdata.add(jTextFieldLogin.getText().toString());        
        DbData.insertDatas("configuration", tempdata, tempcolumn);
        tempdata.clear();
        //pass
        tempdata.add("Email");
        tempdata.add("password");
        tempdata.add(jTextFieldPassword.getText().toString());        
        DbData.insertDatas("configuration", tempdata, tempcolumn);
        tempdata.clear();
        //auth
        tempdata.add("Email");
        tempdata.add("auth");
        tempdata.add(jComboBoxAuth.getSelectedItem().toString());        
        DbData.insertDatas("configuration", tempdata, tempcolumn);
        tempdata.clear();
        //from
        tempdata.add("Email");
        tempdata.add("from");
        tempdata.add(jTextFieldFrom.getText().toString());        
        DbData.insertDatas("configuration", tempdata, tempcolumn);
        tempdata.clear();
        //to
        tempdata.add("Email");
        tempdata.add("to");
        tempdata.add(jTextFieldTo.getText().toString());        
        DbData.insertDatas("configuration", tempdata, tempcolumn);
        tempdata.clear();
        //charset
        tempdata.add("Email");
        tempdata.add("charset");
        tempdata.add(jTextFieldCharset.getText().toString());        
        DbData.insertDatas("configuration", tempdata, tempcolumn);
        tempdata.clear();
        //imagesug
        tempdata.add("Email");
        tempdata.add("imagesug");
        tempdata.add(jTextFieldImage.getText().toString());        
        DbData.insertDatas("configuration", tempdata, tempcolumn);
        tempdata.clear();
        
        if(DbData.rollbakcCommit((Connection)DbConnect.getConnection()))
        {
            Messages.messageInformation("Configuração guardada", "Informação");
            this.dispose();
        }else{
            Messages.messageError("Problema na gravação dos dados", "Aviso");
        }        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void loadJframe()
    {
        try {
            ResultSet rsconf = (ResultSet) DbData.getDataTable("configuration", "conf_tipo", "Email", "", true);
            while(rsconf.next())
            {
                if(rsconf.getString("conf_description").equals("smtpserver"))
                {
                    jTextFieldSmtpserver.setText(rsconf.getString("conf_value"));
                }
                if(rsconf.getString("conf_description").equals("port"))
                {
                    jTextFieldPort.setText(rsconf.getString("conf_value"));
                }
                if(rsconf.getString("conf_description").equals("user"))
                {
                    jTextFieldLogin.setText(rsconf.getString("conf_value"));
                }
                if(rsconf.getString("conf_description").equals("password"))
                {
                    jTextFieldPassword.setText(rsconf.getString("conf_value"));
                }
                if(rsconf.getString("conf_description").equals("auth"))
                {
                    if(rsconf.getString("conf_value").equals("true"))
                    {
                        jComboBoxAuth.setSelectedIndex(0);
                    }else{
                        jComboBoxAuth.setSelectedIndex(1);
                    }                    
                }
                if(rsconf.getString("conf_description").equals("from"))
                {
                    jTextFieldFrom.setText(rsconf.getString("conf_value"));
                }
                if(rsconf.getString("conf_description").equals("to"))
                {
                    jTextFieldTo.setText(rsconf.getString("conf_value"));
                }
                if(rsconf.getString("conf_description").equals("charset"))
                {
                    jTextFieldCharset.setText(rsconf.getString("conf_value"));
                }
                if(rsconf.getString("conf_description").equals("imagesug"))
                {
                    jTextFieldImage.setText(rsconf.getString("conf_value"));
                }
            }
        } catch (SQLException ex) {
            //Logger.getLogger(ConfigurationJFrame.class.getName()).log(Level.SEVERE, null, ex);
            Messages.messageErrorDb("ConfigurationJframe : loadJframe");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxAuth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAuth;
    private javax.swing.JLabel jLabelCharset;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelSmtpserver;
    private javax.swing.JTextField jTextFieldCharset;
    private javax.swing.JTextField jTextFieldFrom;
    private javax.swing.JTextField jTextFieldImage;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldSmtpserver;
    private javax.swing.JTextField jTextFieldTo;
    // End of variables declaration//GEN-END:variables
}
