/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Eleclerc;

import Configuration.configurationJframe;
import Db.DbData;
import Utils.Messages;
import Utils.UtilsJframe;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ricardo
 */
public class CreateUserJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CreateUserJFrame
     */
    public CreateUserJFrame() {
        initComponents();
        this.setTitle("Criação de Utilizador");
        try {
            configurationJframe.inicialConfiguration(this);
        } catch (SQLException ex) {
            //Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            Messages.messageErrorDb("MainJFrame : inicialização jframe");
        }
        new UtilsJframe().fillCombo(jComboBoxSection, true, "", "section", "sec_description");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogin = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelPassword2 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jPasswordFieldPass2 = new javax.swing.JPasswordField();
        jButtonexit = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jLabelSection = new javax.swing.JLabel();
        jComboBoxSection = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelLogin.setText("Login:");

        jLabelPassword.setText("Password:");

        jLabelPassword2.setText("Confirmar Password:");

        jButtonexit.setText("Sair");
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });

        jButtonSave.setText("Guardar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabelSection.setText("Secção");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPassword2)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelLogin)
                            .addComponent(jLabelSection))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldLogin)
                            .addComponent(jPasswordFieldPass)
                            .addComponent(jPasswordFieldPass2)
                            .addComponent(jComboBoxSection, 0, 221, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButtonSave)
                        .addGap(46, 46, 46)
                        .addComponent(jButtonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword2)
                    .addComponent(jPasswordFieldPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSection)
                    .addComponent(jComboBoxSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonexit)
                    .addComponent(jButtonSave))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed
        MaintainUserJFrame mjf = new MaintainUserJFrame();
        mjf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonexitActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if(String.valueOf(jPasswordFieldPass.getPassword()).equals(String.valueOf(jPasswordFieldPass2.getPassword())))
        {
            try {
                ResultSet rs = (ResultSet) DbData.getDataTable("users", "usr_login",
                        jTextFieldLogin.getText(), "", true);
                if(rs.next())
                {
                    Messages.messageInformation("Login existente, escolha outro", "Informação");
                }else{
                    ArrayList value = new ArrayList();
                    ArrayList column = new ArrayList();
                    column.add("usr_login");
                    column.add("usr_password");
                    column.add("usr_section");
                    column.add("usr_enable");
                    value.add(jTextFieldLogin.getText());
                    value.add(String.valueOf(jPasswordFieldPass.getPassword()));
                    ResultSet rsd = (ResultSet) DbData.getDataTable("section", "sec_description",
                            jComboBoxSection.getSelectedItem().toString(), "", true);
                    while(rsd.next())
                    {
                        value.add(rsd.getInt("sec_id"));
                    }
                    value.add(1);
                    
                    if(DbData.insertData("users", value, column) != 0)
                    {
                        Messages.messageInformation("Utilizador criado", "Informação");
                        jButtonexitActionPerformed(evt);
                    }else{
                        Messages.messageError("Utilizador NÃO criado", "Informação");
                    }
                }
            } catch (SQLException ex) {
                //Logger.getLogger(CreateUserJFrame.class.getName()).log(Level.SEVERE, null, ex);
                Messages.messageErrorDb("createUser: botão save");
            }
        }else{
            Messages.messageInformation("Tem que introduzir a mesma password", "Problema na Password");            
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonexit;
    private javax.swing.JComboBox jComboBoxSection;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPassword2;
    private javax.swing.JLabel jLabelSection;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JPasswordField jPasswordFieldPass2;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
