/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Eleclerc;

import Configuration.configurationJframe;
import Utils.Messages;
import Db.DbConnect;
import Db.DbData;
import Utils.Utils;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ricain
 */
public class InicialJFrame extends javax.swing.JFrame {

    private boolean dbok = true;

    /**
     * Creates new form InicialJFrame
     */
    public InicialJFrame() {
        initComponents();
        
        //Verifica a ligação a BD
        if(!DbConnect.dbConnect())
        {
            Messages.messageErrorDb("InicialJFrame: test connection");
            dbok = false;
        }else{
            try {
                //configurações do jframe
                configurationJframe.inicialConfiguration(this);
                this.setTitle("Benvindo");
            } catch (SQLException ex) 
            {
                //Logger.getLogger(InicialJFrame.class.getName()).log(Level.SEVERE, null, ex);
                Messages.messageErrorDb("InicialJFrame (config Jframe)");
            }
        }

        //Vou escrever a versão atual do software.
//        ResultSet rs = (ResultSet) DbData.getLastId("softversion", "vers_id");
//        try 
//        {
//            while(rs.next()){
//                jLblVersion.setText("v"+rs.getString("vers_num"));
//                jLblVersion.setToolTipText(rs.getString("vers_log"));
//            }
//        } catch (SQLException ex) {
//            //Logger.getLogger(InicialJFrame.class.getName()).log(Level.SEVERE, null, ex);
//            Messages.messageErrorDb("InicialJframe : obtenção vers id");
//        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlBackground = new javax.swing.JPanel();
        jLblLogotype = new javax.swing.JLabel();
        jBtnAnonymous = new javax.swing.JButton();
        jBtnClose = new javax.swing.JButton();
        jLblVersion = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jPasswordFieldLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPnlBackground.setBackground(new java.awt.Color(255, 255, 255));

        jLblLogotype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblLogotype.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo01.gif"))); // NOI18N

        jBtnAnonymous.setText("Entrar como Anónimo");
        jBtnAnonymous.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnAnonymous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnonymousActionPerformed(evt);
            }
        });

        jBtnClose.setText("Fechar");
        jBtnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });

        jLblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblVersion.setText("v2.1");
        jLblVersion.setToolTipText("Objetivos nas quebras");

        jLabelLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogin.setText("Login:");
        jLabelLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldLogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabelPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelPassword.setText("Password:");

        jButtonLogin.setText("Entrar");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jPasswordFieldLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPasswordFieldLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldLoginKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPnlBackgroundLayout = new javax.swing.GroupLayout(jPnlBackground);
        jPnlBackground.setLayout(jPnlBackgroundLayout);
        jPnlBackgroundLayout.setHorizontalGroup(
            jPnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBackgroundLayout.createSequentialGroup()
                .addGroup(jPnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlBackgroundLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLogin)
                            .addComponent(jLabelPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPnlBackgroundLayout.createSequentialGroup()
                                .addComponent(jButtonLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(jBtnClose))
                            .addComponent(jTextFieldLogin)
                            .addComponent(jPasswordFieldLogin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBackgroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAnonymous)
                        .addGap(55, 55, 55)))
                .addComponent(jLblVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLblLogotype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnlBackgroundLayout.setVerticalGroup(
            jPnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblLogotype)
                .addGap(27, 27, 27)
                .addGroup(jPnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogin)
                    .addComponent(jBtnClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAnonymous))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAnonymousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnonymousActionPerformed
        //Se não a ligação a BD não faz nada.
        if(dbok)
        {
            AnonymousJFrame anonymous = new AnonymousJFrame(" Não Identifcado", true, 2);
            anonymous.setVisible(true);
            this.dispose();
        }else{
            Messages.messageInformation("Informação", "Contacte o administrador do sistema, obrigado");
        }
    }//GEN-LAST:event_jBtnAnonymousActionPerformed

    /*
     * Método do botão fechar.
     */
    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        //Ao fechar o soft fecha a ligação a BD.
        DbConnect.dbDisconnect(this);
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        login();
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jPasswordFieldLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldLoginKeyPressed
        if(evt.getKeyCode() == 10)
        {
            login();
        }
    }//GEN-LAST:event_jPasswordFieldLoginKeyPressed

    /*
     * Método do botão entrar e de carregar no entrar
     */
    private void login()
    {
        if(Utils.checkLogin(jTextFieldLogin.getText(), jPasswordFieldLogin.getPassword()))
        {
            MainJFrame jf = new MainJFrame();
            jf.setVisible(true);
            this.dispose();
        }else{
            Messages.messageInformation("Login e/ou Palavra Passe errada", "Informação");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnonymous;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLblLogotype;
    private javax.swing.JLabel jLblVersion;
    private javax.swing.JPasswordField jPasswordFieldLogin;
    private javax.swing.JPanel jPnlBackground;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
