/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Eleclerc;

import Type.Users;
import Configuration.configurationJframe;
import Db.DbConnect;
import Db.DbData;
import Utils.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author ricardo
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        this.setTitle("Menu Principal");
        try {
            configurationJframe.inicialConfiguration(this);
        } catch (SQLException ex) {
            //Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            Messages.messageErrorDb("MainJFrame : inicialização jframe");
        }
        jLabelWelcome.setText("Benvindo "+Users.getLogin());
        jLabelToday.setText(UtilsDate.getToday());
        menuAuthorization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogotipo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelToday = new javax.swing.JLabel();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemFileComment = new javax.swing.JMenuItem();
        jMenuItemViewComment = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFileExit = new javax.swing.JMenuItem();
        jMenuResult = new javax.swing.JMenu();
        jMenuItemImportResult = new javax.swing.JMenuItem();
        jMenuItemDeleteVendas = new javax.swing.JMenuItem();
        jMenuItemObjetivos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemViewResults = new javax.swing.JMenuItem();
        jMenuItemViewObjetivos = new javax.swing.JMenuItem();
        jMenuStock = new javax.swing.JMenu();
        jMenuItemImportQuebra = new javax.swing.JMenuItem();
        jMenuItemDeleteQuebras = new javax.swing.JMenuItem();
        jMenuItemInsertObjQuebra = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemViewQuebras = new javax.swing.JMenuItem();
        jMenuItemViewQuebrasObj = new javax.swing.JMenuItem();
        jMenuAdministrator = new javax.swing.JMenu();
        jMenuItemUser = new javax.swing.JMenuItem();
        jMenuItemConfiguration = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabelLogotipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo01.gif"))); // NOI18N

        jLabelWelcome.setText("Benvindo ");

        jMenuBarMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuFile.setText("Ficheiro");

        jMenuItemFileComment.setText("Sugestão");
        jMenuItemFileComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileCommentActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileComment);

        jMenuItemViewComment.setText("Ver Sugestão");
        jMenuItemViewComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewCommentActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemViewComment);
        jMenuFile.add(jSeparator4);

        jMenuItemFileExit.setText("Sair");
        jMenuItemFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileExit);

        jMenuBarMain.add(jMenuFile);

        jMenuResult.setText("Resultados");

        jMenuItemImportResult.setText("Importar Vendas");
        jMenuItemImportResult.setToolTipText("");
        jMenuItemImportResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportResultActionPerformed(evt);
            }
        });
        jMenuResult.add(jMenuItemImportResult);

        jMenuItemDeleteVendas.setText("Eliminar Vendas");
        jMenuItemDeleteVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteVendasActionPerformed(evt);
            }
        });
        jMenuResult.add(jMenuItemDeleteVendas);

        jMenuItemObjetivos.setText("Inserir Objetivos Vendas");
        jMenuItemObjetivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemObjetivosActionPerformed(evt);
            }
        });
        jMenuResult.add(jMenuItemObjetivos);
        jMenuResult.add(jSeparator2);

        jMenuItemViewResults.setText("Ver Vendas");
        jMenuItemViewResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewResultsActionPerformed(evt);
            }
        });
        jMenuResult.add(jMenuItemViewResults);

        jMenuItemViewObjetivos.setText("Ver Objetivos Vendas");
        jMenuItemViewObjetivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewObjetivosActionPerformed(evt);
            }
        });
        jMenuResult.add(jMenuItemViewObjetivos);

        jMenuBarMain.add(jMenuResult);

        jMenuStock.setText("Quebras");

        jMenuItemImportQuebra.setText("Importar Quebras");
        jMenuItemImportQuebra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportQuebraActionPerformed(evt);
            }
        });
        jMenuStock.add(jMenuItemImportQuebra);

        jMenuItemDeleteQuebras.setText("Eliminar Quebras");
        jMenuItemDeleteQuebras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteQuebrasActionPerformed(evt);
            }
        });
        jMenuStock.add(jMenuItemDeleteQuebras);

        jMenuItemInsertObjQuebra.setText("Inserir Objetivos Quebras");
        jMenuItemInsertObjQuebra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInsertObjQuebraActionPerformed(evt);
            }
        });
        jMenuStock.add(jMenuItemInsertObjQuebra);
        jMenuStock.add(jSeparator3);

        jMenuItemViewQuebras.setText("Ver Quebras");
        jMenuItemViewQuebras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewQuebrasActionPerformed(evt);
            }
        });
        jMenuStock.add(jMenuItemViewQuebras);

        jMenuItemViewQuebrasObj.setText("Ver Quebras Objetivos");
        jMenuItemViewQuebrasObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewQuebrasObjActionPerformed(evt);
            }
        });
        jMenuStock.add(jMenuItemViewQuebrasObj);

        jMenuBarMain.add(jMenuStock);

        jMenuAdministrator.setText("Administração");

        jMenuItemUser.setText("Utilizadores");
        jMenuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUserActionPerformed(evt);
            }
        });
        jMenuAdministrator.add(jMenuItemUser);

        jMenuItemConfiguration.setText("Configuração");
        jMenuItemConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfigurationActionPerformed(evt);
            }
        });
        jMenuAdministrator.add(jMenuItemConfiguration);

        jMenuBarMain.add(jMenuAdministrator);

        jMenuExit.setText("Sair");
        jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExitMouseClicked(evt);
            }
        });
        jMenuBarMain.add(jMenuExit);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabelLogotipo, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addGap(151, 151, 151))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelToday)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabelLogotipo, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addGap(134, 134, 134)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWelcome)
                    .addComponent(jLabelToday))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemImportQuebraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportQuebraActionPerformed
        FileChooseJFrame jf = new FileChooseJFrame("quebras");
        //jf.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_jMenuItemImportQuebraActionPerformed

    private void jMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitMouseClicked
        DbConnect.dbDisconnect(this);
    }//GEN-LAST:event_jMenuExitMouseClicked

    private void jMenuItemFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileExitActionPerformed
        DbConnect.dbDisconnect(this);
    }//GEN-LAST:event_jMenuItemFileExitActionPerformed

    private void jMenuItemFileCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileCommentActionPerformed
        AnonymousJFrame anonymous = new AnonymousJFrame(Users.getSection(), false, Users.getNumber());
        anonymous.setVisible(true);
    }//GEN-LAST:event_jMenuItemFileCommentActionPerformed

    private void jMenuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUserActionPerformed
        MaintainUserJFrame jf = new MaintainUserJFrame();
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItemUserActionPerformed

    private void jMenuItemViewCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewCommentActionPerformed
        try {
            ResultSet rs = (ResultSet)DbData.getDataTable("user_section_comment", "", "", "", true);
            //adiciono no array os dados da DB
            
            ArrayList<Comment> comarray = new ArrayList();
            while (rs.next())
            {
                comarray.add(new Comment(rs.getInt("com_id"), rs.getString("usr_login"), rs.getString("sec_description"),
                        rs.getString("com_comments")));
            }

            Object[][] donnees = new Object[comarray.size()][4];
            for(int i=0;i<comarray.size();i++)
            {
                Comment cm = comarray.get(i);
                donnees[i][0] = cm.getId();
                donnees[i][1] = cm.getLogin();
                donnees[i][2] = cm.getSection();
                donnees[i][3] = cm.getComment();
            }
            String[] entetes = {"id", "Utilizador", "Secção", "Commentario"};
            //numero da minha colune que estou a editar para recuperar mais tarde

            JTable jtable = new UtilsTable().FillJTable(donnees, entetes, 88, 1);
            TableDataJFrame tjf = new TableDataJFrame(jtable);
            tjf.setVisible(true); 
            
        } catch (SQLException ex) {
            //Logger.getLogger(MaintainUserJFrame.class.getName()).log(Level.SEVERE, null, ex);
            Messages.messageErrorDb("MainJframe : Ver Sugestão");
        }
        
        
    }//GEN-LAST:event_jMenuItemViewCommentActionPerformed

    private void jMenuItemViewQuebrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewQuebrasActionPerformed
        // TODO add your handling code here:
        //new UtilsGraph().CreatePie();
        ViewQuebrasJFrame vqjf = new ViewQuebrasJFrame();
        vqjf.setVisible(true);
    }//GEN-LAST:event_jMenuItemViewQuebrasActionPerformed

    private void jMenuItemImportResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportResultActionPerformed
        FileChooseJFrame jf = new FileChooseJFrame("vendas");
    }//GEN-LAST:event_jMenuItemImportResultActionPerformed

    private void jMenuItemViewResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewResultsActionPerformed
        Messages.messageInformation("Ainda não implementado", "Informação");
    }//GEN-LAST:event_jMenuItemViewResultsActionPerformed

    private void jMenuItemObjetivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemObjetivosActionPerformed
        InsertObjetivo io = new InsertObjetivo(0);
        io.setVisible(true);
    }//GEN-LAST:event_jMenuItemObjetivosActionPerformed

    private void jMenuItemDeleteQuebrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteQuebrasActionPerformed
        ImportJFrame ijf = new ImportJFrame("", "eliminarquebras");
        ijf.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeleteQuebrasActionPerformed

    private void jMenuItemViewObjetivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewObjetivosActionPerformed
        ViewObjetivos vojf = new ViewObjetivos(0);
        vojf.setVisible(true);
    }//GEN-LAST:event_jMenuItemViewObjetivosActionPerformed

    private void jMenuItemConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigurationActionPerformed
        ConfigurationJFrame cjf = new ConfigurationJFrame();
        cjf.setVisible(true);
    }//GEN-LAST:event_jMenuItemConfigurationActionPerformed

    private void jMenuItemInsertObjQuebraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsertObjQuebraActionPerformed
        InsertObjetivo io = new InsertObjetivo(1);
        io.setVisible(true);
    }//GEN-LAST:event_jMenuItemInsertObjQuebraActionPerformed

    private void jMenuItemViewQuebrasObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewQuebrasObjActionPerformed
        ViewObjetivos vojf = new ViewObjetivos(1);
        vojf.setVisible(true);
    }//GEN-LAST:event_jMenuItemViewQuebrasObjActionPerformed

    private void jMenuItemDeleteVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteVendasActionPerformed
        ImportJFrame ijf = new ImportJFrame("", "eliminarvendas");
        ijf.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeleteVendasActionPerformed

    /*
     * Método que verifica se o user tem acesso ao menu ou não
     */
    private void menuAuthorization()
    {
        ResultSet rs = (ResultSet) DbData.getDataTable("menumain", "", "", "", true);
        try {
            while (rs.next())
            {
                if(!Users.getAuthorization(rs.getString("menu_description")))
                {
                    hideMenu(rs.getString("menu_description"));
                }
            }
        } catch (SQLException ex) {
            //Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            Messages.messageErrorDb("Mainjframe: hidemenu");
        }
    }
    
    private void hideMenu(String st)
    {
        switch (st)
        {
            case "Ficheiro":// 10
                jMenuFile.setVisible(false);
                break;
            case "Sugestão":// 11
                jMenuItemFileComment.setVisible(false);
                break;
            case "Ver Sugestão":// 12
                jMenuItemViewComment.setVisible(false);
                break;
            case "Quebras":// 20
                jMenuStock.setVisible(false);
                break;
            case "Importar Quebras":// 21
                jMenuItemImportQuebra.setVisible(false);
                break;
            case "Ver Quebras":// 22 
                jMenuItemViewQuebras.setVisible(false);
                break;                
            case "Eliminar Quebras":// 23
                jMenuItemDeleteQuebras.setVisible(false);
                break;
            case "Inserir Objetivos Quebras"://24
                jMenuItemInsertObjQuebra.setVisible(false);
                break;
            case "Ver Quebras Objetivos"://25
                jMenuItemViewQuebrasObj.setVisible(false);
                break;
            case "Administração"://30
                jMenuAdministrator.setVisible(false);
                break;
            case "Utilizadores"://31
                jMenuItemUser.setVisible(false);
                break;
            case "Configuração"://32
                jMenuItemConfiguration.setVisible(false);
                break;                
            case "Resultados"://40
                jMenuResult.setVisible(false);
                break;
            case "Importar Vendas"://41
                jMenuItemImportResult.setVisible(false);
                break;
            case "Ver Vendas"://42
                jMenuItemViewResults.setVisible(false);
                break;
            case "Inserir Objetivos Vendas"://43
                jMenuItemObjetivos.setVisible(false);
                break; 
            case "Ver Objetivos Vendas"://44
                jMenuItemViewObjetivos.setVisible(false);
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLogotipo;
    private javax.swing.JLabel jLabelToday;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JMenu jMenuAdministrator;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemConfiguration;
    private javax.swing.JMenuItem jMenuItemDeleteQuebras;
    private javax.swing.JMenuItem jMenuItemDeleteVendas;
    private javax.swing.JMenuItem jMenuItemFileComment;
    private javax.swing.JMenuItem jMenuItemFileExit;
    private javax.swing.JMenuItem jMenuItemImportQuebra;
    private javax.swing.JMenuItem jMenuItemImportResult;
    private javax.swing.JMenuItem jMenuItemInsertObjQuebra;
    private javax.swing.JMenuItem jMenuItemObjetivos;
    private javax.swing.JMenuItem jMenuItemUser;
    private javax.swing.JMenuItem jMenuItemViewComment;
    private javax.swing.JMenuItem jMenuItemViewObjetivos;
    private javax.swing.JMenuItem jMenuItemViewQuebras;
    private javax.swing.JMenuItem jMenuItemViewQuebrasObj;
    private javax.swing.JMenuItem jMenuItemViewResults;
    private javax.swing.JMenu jMenuResult;
    private javax.swing.JMenu jMenuStock;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
